export async function GET() {
  return Response.json({
    name: "InkGate Agent Network",
    version: "1.0.0",
    network: "X Layer Mainnet",
    chainId: 196,
    description: "3 autonomous AI agents for crypto research, fact-checking and writing",
    paymentToken: "USDC",
    paymentAddress: process.env.PAYMENT_RECIPIENT_ADDRESS,
    agents: [
      {
        id: "research-agent",
        name: "InkGate Research Agent",
        address: process.env.NEXT_PUBLIC_AGENT1_ADDRESS,
        description: "Researches any crypto topic with live OKX market data",
        capabilities: ["web-research", "market-data", "crypto-analysis"],
        pricePerCall: "0.004 USDC",
        endpoint: "/api/custom",
        method: "POST",
        input: { topic: "string", txHash: "string" },
        output: { content: "string", agentPipeline: "object" },
      },
      {
        id: "factcheck-agent",
        name: "InkGate Fact Check Agent",
        address: process.env.NEXT_PUBLIC_AGENT2_ADDRESS,
        description: "Verifies and fact-checks any crypto claim or research",
        capabilities: ["fact-checking", "verification", "analysis"],
        pricePerCall: "0.003 USDC",
        endpoint: "/api/custom",
        method: "POST",
        input: { topic: "string", txHash: "string" },
        output: { content: "string" },
      },
      {
        id: "writer-agent",
        name: "InkGate Writer Agent",
        address: process.env.NEXT_PUBLIC_AGENT3_ADDRESS,
        description: "Writes compelling crypto articles and content",
        capabilities: ["content-writing", "article-generation", "copywriting"],
        pricePerCall: "0.003 USDC",
        endpoint: "/api/custom",
        method: "POST",
        input: { topic: "string", txHash: "string" },
        output: { content: "string" },
      },
      {
        id: "debate-agent",
        name: "InkGate Debate System",
        address: process.env.NEXT_PUBLIC_AGENT1_ADDRESS,
        description: "Bull vs Bear debate with Judge Agent verdict on any crypto topic",
        capabilities: ["debate", "analysis", "verdict"],
        pricePerCall: "0.01 USDC",
        endpoint: "/api/debate",
        method: "POST",
        input: { topic: "string", txHash: "string" },
        output: { bull: "string", bear: "string", winner: "string", reasoning: "string" },
      },
      {
        id: "predictor-agent",
        name: "InkGate Predictor Agent",
        address: process.env.NEXT_PUBLIC_AGENT1_ADDRESS,
        description: "Makes 24-hour crypto price predictions using live OKX data",
        capabilities: ["price-prediction", "market-analysis", "forecasting"],
        pricePerCall: "0.01 USDC",
        endpoint: "/api/predictions",
        method: "POST",
        input: { txHash: "string" },
        output: { prediction: "string", direction: "string", confidence: "number" },
      },
    ],
    docs: "https://github.com/Mestarkris/inkgate",
    contact: "https://x.com/InkGateAI",
  });
}